language: node_js
node_js:
- '8'
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_script:
- npm install
before_deploy:
- npm run prerelease
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
        secure: hRgGeDK/tiTEiBD/6aIuaTkMiT/dEptb8gPAFtSX/kohKHpuFLcj2/ZtsV1PJR3VLGgErGLQkH1dgWarGqr5vKmuq9yofGU6dZHUaA08s0JzsTxc8Jv2QvJ1krDBNzGotD7/9jfDp6VmDRhzlqHO6h9PNBkNzR60vfAKen1XgY9w+W0Vqc9Ye/4QPRKkXZqh5vxJKVaG8ODUWGY7Azmd0PYQu7Lh+RP8H1CO6w/N7mAvDjYcOC8djkq2vfcKGjmQuOdA8tTZubDM6CHaNJH514cNaIVS1a2aUY+++ZTzAzAm8yjIF9mh85CVu/zXCO5S4vmVm9YRE20gcdYI3QRjDouahKrXFIvNaZHIOPWbkX1pYv4B2ZBCbsjOpoEOVIgfIVuPNJB8xSiAM1noDqlwQck2UXUuypFmcH/eks26R2ZTVowPsd4X3AoDZ+367H66aQokS3UPYXobfpwI8DzLrSfQ6YvPup5kjRY2hU79IVicUj6mlOVzNfpJSRP0J55hxgEpBEr11glzgVyfYOZzwDLs/081umxVkL0jemJJZfW77PQWX63RG6X6tScXK1pCdBsEHuCEWMzUAnpkdonWuDlRurCtmC9thW7KPPehh8qkOCEBsKql/R1gxtwjPUbt5pZDynPjSY7FNF3g0oandKiEdMDNApLMiZtBWhwgkFY=
    file: dist.zip
    on:
        tags: true
        branch: master
        repo: higlass/higlass-time-interval-track
  - provider: npm
    skip_cleanup: true
    email: pkerpedjiev@gmail.com
    api_key:
      secure: DGIncZhOYiJZVQc2kg5eMe/dFfaJDS6hMx9rAkDNyHg2GDeYvP/dFmXvJMllR2m5c82UuNt2AuKZljC8QzK4H2ykxq18Rfl1Dw30iv7oMf4qsW/eK8+4Lzz6qyvlAAYfCFmOzDALe0OEQtq1DZRzojy4c/wAbLJzXlo+qQQKJuD0YRNiT/X6286OdRsh9F43K//cJyTdtSfWfqFN3jRgACoQIxrkqU9quNP2cvUpXTraPLR6s7t89+fRnVI0S1noZRMzlF7Qu7gQxDbrEblYPuUwqYSCrvninHiEQp5o9logm5cUwJkOeaIlYUcjEs3n542yLbLi2AkU+KktayxBEfdi1hZn+mB3qIF6sE61IU9Doq/OI2DFLkSypddYe/7cc+SUrR+v+xOnwTYIjqlLZ2f5WEuI7wni6RTNast1jj4Jm1dp7qyW0YKm9mKDJvsgLj/Oyc849Lr33w9wOAzMqgnSMNr0G7athobq4M1YNjkKsMnjz1lBgB5Tc9NQddMcOgOP58sgKI+vrVWKOECUn0znDhIKCtx27pBKzIYf0USPFeWWtkSKfbppIFS2+NXV4SsXxeF0txweqXYGtQ7VxvbNvApk9ObAHNoc32oOD02hqQAH9nbUq8pi1SyKrdWI1YpuWA/2Op1wSIMKFKlOWuv1VK0HYbRaLllx3QVB6gA=
    on:
      branch: master
      tags: true
      repo: higlass/higlass-time-interval-track
